baseURL = "http://pranavi-boyalakuntla.com/"
languageCode = "en-us"
title = "Pranavi Boyalakuntla"
theme = "hugo-theme-console"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
  
  [[params.navlinks]]
  name = "blog/"
  url = "blog/"

  [[params.navlinks]]
  name = "resume/"
  url = "resume/"

  [[params.navlinks]]
  name = "contact/"
  url = "contact/"