baseURL = "https://pranavi.space"
languageCode = "en-us"
title = "Pranavi Boyalakuntla"
theme = "hugo-theme-console"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
  
  [[params.navlinks]]
  name = "publications/"
  url = "publications/"

  [[params.navlinks]]
  name = "resume/"
  url = "resume/"

  [[params.navlinks]]
  name = "contact/"
  url = "contact/"